eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
server:
  port: 5000
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.105.40.183:3306/lol-show?useUnicode=true&characterEncoding=utf8
    username: root
    password: rootroot
  application:
    name: LOL-show-member-consumer
  thymeleaf:
    cache: false
  redis:
    host: 47.105.40.183
ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 600000

