eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
server:
  port: 4000
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lol-show?useUnicode=true&characterEncoding=utf8
    username: root
    password: rootroot
  application:
    name: LOL-show-hero-consumer
  thymeleaf:
    cache: false
  redis:
    host: 127.0.0.1

